- hosts: masters
  become: yes
  tasks:

# reset kubernetes cluster
    - name: reset clusters
      shell: |
              kubeadm reset -f

    - name: remove existing cluster configs for user kube
      file:
        path: "{{ item }}"
        state: absent
      with_items:
       - /home/kube/.kube/
       - /etc/kubernetes/
       - /var/lib/kubelet/
       - /var/lib/etcd/